; Self-Hosted Crypto Account Ownership Credential (SCAC)
; DocType: io.github.masanork.tobari.crypto_account_cert

crypto_account_cert = {
    "io.github.masanork.tobari.crypto_account" => {
        "accounts" => [+ AccountEntry],
        "verification_level" => tstr,
        "issuance_date" => tdate,
        "expiry_date" => tdate,
        ? "kyc_provider_id" => tstr
    },
    "io.github.masanork.tobari.person" => {
        "family_name" => tstr,
        "given_name" => tstr,
        "birth_date" => full-date,
        ? "nationality" => tstr,
        "document_type" => "passport" / "jpki"
    }
}

AccountEntry = {
    "chain" => tstr,
    "chain_id" => tstr,
    "address" => tstr,
    "binding" => tstr
}
